#!/usr/bin/env bash
# Usage: ./0-world_wide_web <domain> <subdomain>
# Display information about subdomains.

domain_information () {
    local result
    result=$(dig "$2.$1" +short)

    if [ -z "$result" ]; then
        echo "The subdomain $2 does not exist."
    else
        echo "$result" | awk -v sub="$2" '{print "The subdomain " sub " is a A record and points to " $1}'
    fi
}

if [ "$#" = 1 ]; then
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
elif [ "$#" = 2 ]; then
    domain_information "$1" "$2"
else
    echo "Usage: $0 <domain> [<subdomain>]"
fi

