#!/bin/bash
# Create an RSA key pair

# Define key name and passphrase
KEY_NAME="school"
PASSPHRASE="betty"

# Generate RSA key pair
ssh-keygen -t rsa -b 4096 -f $KEY_NAME -N "$PASSPHRASE"

# Output message
echo "RSA key pair created:"
ls -l $KEY_NAME $KEY_NAME.pub

